/*
 To change this license header, choose License Headers in Project Properties.
 To change this template file, choose Tools | Templates
 and open the template in the editor.
 */
package panels;

import static dbviewer.globals.GlobalVariables.CRLF;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.InvalidPathException;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.nio.file.StandardCopyOption;
import javax.swing.JFrame;
import javax.swing.JPanel;

/**

 @author Mark Ferguson
 */
public class Panel4T5Backup extends Panel4 {

  /**

   @param args strings to start
   */
  public static void main(String[] args) {
    JPanel jp = new Panel4T5Backup();
    JFrame jf = new Frame4(jp);
  }

  /**
   Creates new form Panel4T5Backup
   */
  public Panel4T5Backup() {
    initComponents();
  }

  /**
   This method is called from within the constructor to
   initialize the form.
   WARNING: Do NOT modify this code. The content of this method is
   always regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    jScrollPane1 = new javax.swing.JScrollPane();
    jta = new javax.swing.JTextArea();
    jButton1 = new javax.swing.JButton();

    jta.setColumns(20);
    jta.setRows(5);
    jScrollPane1.setViewportView(jta);

    jButton1.setText("Backup");
    jButton1.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jButton1ActionPerformed(evt);
      }
    });

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
    this.setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
        .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 99, Short.MAX_VALUE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE))
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
      .addGroup(layout.createSequentialGroup()
        .addComponent(jButton1)
        .addGap(0, 0, Short.MAX_VALUE))
    );
  }// </editor-fold>//GEN-END:initComponents

  private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    try {
      String args0 = "D:\\JAVA8\\TFX";
      String args1 = "E:\\Backup\\TFX";
      Path source = Paths.get(args0);
      Path target = Paths.get(args1);
      // Copy the file.
      Files.copy(source, target, StandardCopyOption.REPLACE_EXISTING);
      jta.append(args0 + CRLF);
      jta.append(args1 + CRLF);
      jta.append(CRLF);

      //REPEAT
      args0 = "C:\\T5";
      args1 = "E:\\Backup\\T5";
      source = Paths.get(args0);
      target = Paths.get(args1);
      Files.copy(source, target, StandardCopyOption.REPLACE_EXISTING);
      jta.append(args0 + CRLF);
      jta.append(args1 + CRLF);
      jta.append(CRLF);

    } catch (InvalidPathException e) {
      System.out.println("Path Error " + e);
    } catch (IOException e) {
      System.out.println("I/O Error " + e);
    }
  }//GEN-LAST:event_jButton1ActionPerformed

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton jButton1;
  private javax.swing.JScrollPane jScrollPane1;
  private javax.swing.JTextArea jta;
  // End of variables declaration//GEN-END:variables
}
