/*

 Copyright (C) 2014 Mark Ferguson



 This program is free software: you can redistribute it and/or modify

 it under the terms of the GNU General Public License as published by

 the Free Software Foundation, either version 3 of the License, or

 (at your option) any later version.



 This program is distributed in the hope that it will be useful,

 but WITHOUT ANY WARRANTY; without even the implied warranty of

 MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the

 GNU General Public License for more details.



 You should have received a copy of the GNU General Public License

 along with this program.  If not, see <http://www.gnu.org/licenses/>.

 */
package panels;

import dbviewer.globals.GlobalVariables;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.Image;
import java.awt.Toolkit;
import java.awt.geom.AffineTransform;
import javax.swing.ImageIcon;
import javax.swing.JFrame;

/**
 <p>
 @author Your Name Mark Ferguson maggot.iiss@sky.com
 */
public class Panel4Pic extends Panel4 {

  static Panel4 jp;
  static Frame4 jf;
  private int num;
  Image image;
  ImageIcon imic;
  Graphics g;
  Graphics2D g2;

  /**
   <p>
   @param args strings to start
   */
  public static void main(String[] args) {
    jp = new Panel4Pic();
    jf = new Frame4(jp, "Panel4Pic");
    jf.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
  }

  /**
   Creates new form Panel4Pic
   */
  public Panel4Pic() {
    this.g = getGraphics();
    this.g2 = (Graphics2D) g;
    initComponents();
    image = Toolkit.getDefaultToolkit().getImage(GlobalVariables.HAR
      + "/SHI/BR.gif");
  }

  /**
   <p>
   @param g Graphics
   */
  @Override
  public void paintComponent(Graphics g) {
    super.paintComponent(g);
    Graphics2D g2d = (Graphics2D) g; // Create a Java2D version of g.
    int wid = image.getWidth(null);
    int hgt = image.getHeight(null);
    int x = wid / 2;
    int y = hgt / 2;
    int diag = (int) Math.sqrt((wid * wid) + (hgt * hgt));
    AffineTransform start = g2d.getTransform();
    start.setToQuadrantRotation(num, wid / 2, hgt / 2);
    g2d.drawImage(image, start, this);
  }

  /**
   This method is called from within the constructor to initialize the form.
   WARNING: Do NOT modify this code. The content of this method is always
   regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    setBackground(new java.awt.Color(255, 255, 255));
    setOpaque(false);
    setPreferredSize(new java.awt.Dimension(100, 100));
    addMouseListener(new java.awt.event.MouseAdapter() {
      public void mouseClicked(java.awt.event.MouseEvent evt) {
        formMouseClicked(evt);
      }
    });

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
    this.setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGap(0, 100, Short.MAX_VALUE)
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGap(0, 100, Short.MAX_VALUE)
    );
  }// </editor-fold>//GEN-END:initComponents

  private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
    ++num;
    if (num == 4) {
      num = 0;
    }
    repaint();
  }//GEN-LAST:event_formMouseClicked
  // Variables declaration - do not modify//GEN-BEGIN:variables
  // End of variables declaration//GEN-END:variables
}
