/*
 To change this license header, choose License Headers in Project Properties.
 To change this template file, choose Tools | Templates
 and open the template in the editor.
 */
package linkpictext;

import static dbviewer.globals.GlobalVariables.CRLF;
import static dbviewer.globals.GlobalVariables.FS;
import java.awt.event.ActionEvent;
import java.awt.event.MouseEvent;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.io.PrintWriter;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JTextField;
import static linkpictext.Panel4LPT.category;
import static linkpictext.Panel4LPT.getLinesFromFile;
import static linkpictext.Panel4LPT.html;
import static linkpictext.Panel4LPT.item;
import static linkpictext.Panel4LPT.links;
import panels.Frame4;
import panels.Panel4;
import panels.Panel4T5Locator;

/**

 @author Mark Ferguson
 */
public class Panel4Add extends Panel4 {

  static JPanel jp;
  static JFrame jf;
  private static JTextField[] jtas;
  private static JLabel[] labs;
  ActionEvent ae;
  MouseEvent me;

  /**

   @param string
   */
  public static void main(String[] string) {
    jp = new Panel4Add();
    jf = new Frame4();
    jf.setVisible(false);
    jf.add(jp);
    jf.setDefaultCloseOperation(JFrame.HIDE_ON_CLOSE);
    jf.setBounds(800, 0, 600, 600);
//    jf.setVisible(true);
  }

  /**
   Creates new form Panel4Add
   */
  public Panel4Add() {
    initComponents();
    jtas = new JTextField[]{
      xmldoc, xsldoc, comment, title, script, header, heading, pics, picture,
      intro, text, footnote, footer, sec, sub, sys, name
    };
    labs = new JLabel[]{
      jLabel1, jLabel2, jLabel3, jLabel4, jLabel5, jLabel6, jLabel7, jLabel8,
      jLabel9, jLabel10, jLabel11, jLabel12, jLabel13, jLabel14, jLabel15,
      jLabel16, jLabel17
    };
  }

  private void saveAction(ActionEvent evt) {
    File def = new File(Panel4LPT.links + "Default.html");
    String[] lines = getLinesFromFile(def);
    File file;
    file = new File(links + category.getSelectedItem().toString() + FS + item
      .getSelectedItem().toString() + ".html");
    System.out.println("file " + " = " + file.toString());
    html.setToolTipText(file.toString());
    html.setText("");
    for (int i = 0; i < lines.length; i++) {
      for (int j = 0; j < labs.length; j++) {
        if (lines[i].contains(labs[j].getText())) {
          lines[i] = lines[i].replace(labs[j].getText(), jtas[j].getText());
          lines[i] = lines[i].replace("\\", "/");
        }
      }
//      if (!lines[i].equals("")) {
      html.append(lines[i] + CRLF);
//      }
    }
    for (int i = 0; i < jtas.length; i++) {
      System.out.println("Replace " + labs[i].getText() + " With " + jtas[i]
        .getText() + " in file " + file.toString());
    }
    String[] txt = null;
    String txtx = "";
    txt = html.getText().split(CRLF);
    for (int i = 0; i < txt.length; i++) {
      System.out.println(txt[i]);
      txtx += txt[i] + CRLF;
    }
//    saveTextFile(links + category.getSelectedItem().toString(), item.getSelectedItem().toString(), ".html", txtx);
    String dest = Panel4T5Locator.getSysPath().trim() + FS
      + Panel4T5Locator.jcb4Sys
        .getSelectedItem().toString().trim();
    dest = dest.replace(".csv", "");
    saveTextFile(dest, item.getSelectedItem().toString(), ".html", txtx);
    System.out.println("dest" + " = " + dest);
  }

  /**
   <p>
   @param folder for file
   @param name   title of file
   @param ext    extension of file
   @param txt    to save
   */
  public static void saveTextFile(String folder, String name, String ext,
    String txt) {
    String string = null;
    try {
      string = folder + FS + name + "." + ext.toLowerCase();
      string = string.replace(FS + FS, FS);
      string = string.replace("..", ".");
//      JOptionPane.showMessageDialog(null, string);
      if (string.contains("null")) {

      } else {
        try (PrintWriter out = new PrintWriter(new FileWriter(new File(string)))) {
          out.print(txt);
          out.close();
        }
      }
    } catch (IOException ex) {
      System.out.println("119 IOException" + " = " + ex);
    }
  }

  /**
   This method is called from within the constructor to
   initialize the form.
   WARNING: Do NOT modify this code. The content of this method is
   always regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    jLabel1 = new javax.swing.JLabel();
    xmldoc = new javax.swing.JTextField();
    jLabel2 = new javax.swing.JLabel();
    xsldoc = new javax.swing.JTextField();
    jLabel3 = new javax.swing.JLabel();
    comment = new javax.swing.JTextField();
    jLabel4 = new javax.swing.JLabel();
    title = new javax.swing.JTextField();
    jLabel5 = new javax.swing.JLabel();
    script = new javax.swing.JTextField();
    jLabel6 = new javax.swing.JLabel();
    header = new javax.swing.JTextField();
    jLabel7 = new javax.swing.JLabel();
    heading = new javax.swing.JTextField();
    jLabel8 = new javax.swing.JLabel();
    pics = new javax.swing.JTextField();
    jLabel9 = new javax.swing.JLabel();
    picture = new javax.swing.JTextField();
    jLabel10 = new javax.swing.JLabel();
    intro = new javax.swing.JTextField();
    jLabel11 = new javax.swing.JLabel();
    text = new javax.swing.JTextField();
    jLabel12 = new javax.swing.JLabel();
    footnote = new javax.swing.JTextField();
    jLabel13 = new javax.swing.JLabel();
    footer = new javax.swing.JTextField();
    jLabel14 = new javax.swing.JLabel();
    sec = new javax.swing.JTextField();
    jLabel15 = new javax.swing.JLabel();
    sub = new javax.swing.JTextField();
    jLabel16 = new javax.swing.JLabel();
    sys = new javax.swing.JTextField();
    jLabel17 = new javax.swing.JLabel();
    name = new javax.swing.JTextField();
    Save = new javax.swing.JButton();

    setBackground(new java.awt.Color(0, 0, 0));
    setOpaque(true);

    jLabel1.setForeground(java.awt.Color.lightGray);
    jLabel1.setText("XMLDOC");
    jLabel1.setToolTipText("");

    xmldoc.setText("XMLDOC");

    jLabel2.setForeground(java.awt.Color.lightGray);
    jLabel2.setText("XSLDOC");

    xsldoc.setText("XSLDOC");

    jLabel3.setForeground(java.awt.Color.lightGray);
    jLabel3.setText("COMMENT");

    comment.setText("COMMENT");

    jLabel4.setForeground(java.awt.Color.lightGray);
    jLabel4.setText("TITLE");

    title.setText("TITLE");

    jLabel5.setForeground(java.awt.Color.lightGray);
    jLabel5.setText("SCRIPT");

    script.setText("SCRIPT");

    jLabel6.setForeground(java.awt.Color.lightGray);
    jLabel6.setText("HEADER");

    header.setText("HEADER");

    jLabel7.setForeground(java.awt.Color.lightGray);
    jLabel7.setText("HEADING");

    heading.setText("HEADING");

    jLabel8.setForeground(java.awt.Color.lightGray);
    jLabel8.setText("PICS");

    pics.setText("PICS");

    jLabel9.setForeground(java.awt.Color.lightGray);
    jLabel9.setText("PICTURE");

    picture.setText("PICTURE");

    jLabel10.setForeground(java.awt.Color.lightGray);
    jLabel10.setText("INTRO");

    intro.setText("INTRO");

    jLabel11.setForeground(java.awt.Color.lightGray);
    jLabel11.setText("TEXT");

    text.setText("TEXT");

    jLabel12.setForeground(java.awt.Color.lightGray);
    jLabel12.setText("FOOTNOTE");

    footnote.setText("FOOTNOTE");

    jLabel13.setForeground(java.awt.Color.lightGray);
    jLabel13.setText("FOOTER");

    footer.setText("FOOTER");

    jLabel14.setForeground(java.awt.Color.lightGray);
    jLabel14.setText("SEC");

    sec.setText("Spinward Marches");

    jLabel15.setForeground(java.awt.Color.lightGray);
    jLabel15.setText("SUB");

    sub.setText("C Regina");

    jLabel16.setForeground(java.awt.Color.lightGray);
    jLabel16.setText("SYS");

    sys.setText("1705 Efate");

    jLabel17.setForeground(java.awt.Color.lightGray);
    jLabel17.setText("NAME");

    name.setText("1705");

    Save.setText("Save");
    Save.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        SaveActionPerformed(evt);
      }
    });

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
    this.setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(jLabel9)
          .addComponent(jLabel10)
          .addComponent(jLabel11)
          .addComponent(jLabel12)
          .addComponent(jLabel4)
          .addComponent(jLabel13)
          .addComponent(jLabel5)
          .addComponent(jLabel14)
          .addComponent(jLabel6)
          .addComponent(jLabel15)
          .addComponent(jLabel7)
          .addComponent(jLabel16)
          .addComponent(jLabel8)
          .addComponent(jLabel1)
          .addComponent(jLabel2)
          .addComponent(jLabel3)
          .addComponent(jLabel17))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(picture, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 179, Short.MAX_VALUE)
          .addComponent(intro, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 179, Short.MAX_VALUE)
          .addComponent(text, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 179, Short.MAX_VALUE)
          .addComponent(footnote, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 179, Short.MAX_VALUE)
          .addComponent(title, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 179, Short.MAX_VALUE)
          .addComponent(footer, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 179, Short.MAX_VALUE)
          .addComponent(script, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 179, Short.MAX_VALUE)
          .addComponent(sec, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 179, Short.MAX_VALUE)
          .addComponent(header, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 179, Short.MAX_VALUE)
          .addComponent(sub, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 179, Short.MAX_VALUE)
          .addComponent(heading, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 179, Short.MAX_VALUE)
          .addComponent(sys, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 179, Short.MAX_VALUE)
          .addComponent(pics, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 179, Short.MAX_VALUE)
          .addComponent(xmldoc, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 179, Short.MAX_VALUE)
          .addComponent(xsldoc, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 179, Short.MAX_VALUE)
          .addComponent(comment, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 179, Short.MAX_VALUE)
          .addComponent(name, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 179, Short.MAX_VALUE)))
      .addGroup(layout.createSequentialGroup()
        .addGap(80, 80, 80)
        .addComponent(Save))
    );

    layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jLabel1, jLabel10, jLabel11, jLabel12, jLabel13, jLabel14, jLabel15, jLabel16, jLabel17, jLabel2, jLabel3, jLabel4, jLabel5, jLabel6, jLabel7, jLabel8, jLabel9});

    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(jLabel1)
          .addComponent(xmldoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(xsldoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(jLabel2))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(comment, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(jLabel3))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(title, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(jLabel4))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(script, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(jLabel5))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(header, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(jLabel6))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(layout.createSequentialGroup()
            .addGap(2, 2, 2)
            .addComponent(jLabel7))
          .addComponent(heading, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(pics, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(jLabel8))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(picture, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(jLabel9))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(jLabel10)
          .addComponent(intro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(jLabel11))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(footnote, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(jLabel12))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(footer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(jLabel13))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(sec, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(jLabel14))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(sub, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(jLabel15))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(sys, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(jLabel16))
        .addGap(41, 41, 41)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(jLabel17))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
        .addComponent(Save))
    );

    layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jLabel1, jLabel10, jLabel11, jLabel12, jLabel13, jLabel14, jLabel15, jLabel16, jLabel17, jLabel2, jLabel3, jLabel4, jLabel5, jLabel6, jLabel7, jLabel8, jLabel9});

  }// </editor-fold>//GEN-END:initComponents

  private void SaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveActionPerformed
    saveAction(evt);
  }//GEN-LAST:event_SaveActionPerformed

  // Variables declaration - do not modify//GEN-BEGIN:variables
  static javax.swing.JButton Save;
  public static javax.swing.JTextField comment;
  public static javax.swing.JTextField footer;
  public static javax.swing.JTextField footnote;
  public static javax.swing.JTextField header;
  public static javax.swing.JTextField heading;
  public static javax.swing.JTextField intro;
  private javax.swing.JLabel jLabel1;
  private javax.swing.JLabel jLabel10;
  private javax.swing.JLabel jLabel11;
  private javax.swing.JLabel jLabel12;
  private javax.swing.JLabel jLabel13;
  private javax.swing.JLabel jLabel14;
  private javax.swing.JLabel jLabel15;
  private javax.swing.JLabel jLabel16;
  private javax.swing.JLabel jLabel17;
  private javax.swing.JLabel jLabel2;
  private javax.swing.JLabel jLabel3;
  private javax.swing.JLabel jLabel4;
  private javax.swing.JLabel jLabel5;
  private javax.swing.JLabel jLabel6;
  private javax.swing.JLabel jLabel7;
  private javax.swing.JLabel jLabel8;
  private javax.swing.JLabel jLabel9;
  public static javax.swing.JTextField name;
  public static javax.swing.JTextField pics;
  public static javax.swing.JTextField picture;
  public static javax.swing.JTextField script;
  public static javax.swing.JTextField sec;
  public static javax.swing.JTextField sub;
  public static javax.swing.JTextField sys;
  public static javax.swing.JTextField text;
  public static javax.swing.JTextField title;
  public static javax.swing.JTextField xmldoc;
  public static javax.swing.JTextField xsldoc;
  // End of variables declaration//GEN-END:variables
}
