/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package open;

import javax.swing.JFrame;
import javax.swing.JPanel;
import empires.Empire;
import javax.swing.JOptionPane;
import panels.Panel4T5Locator;
import starters.Boxer;
import wordgen.Panel4WordGen;

/**
 *
 * @author Mark Ferguson
 */
public class P4Start extends javax.swing.JPanel {

    String[] args = {""};

    /**
     *
     * @param args
     */
    public static void main(String[] args) {
        System.out.println(args.toString());
        if (args[0].isEmpty()) {
            JOptionPane.showMessageDialog(null, "args is empty");
        }
        if ("open.P4Start".equals(args[0])) {
            JPanel jp = new P4Start();
            JFrame jf = new JFrame();
            jf.setTitle(args[0]);
            jf.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
            jf.setSize(400, 400);
            jf.setContentPane(jp);
            jf.setVisible(true);
        }
        if ("empires.Empire".equals(args[0])) {
            empires.Empire.main(args);
        }
        if ("applets.Calculator".equals(args[0])) {
            applets.Calculator.main(args);
        }
        if ("applets.FontTest".equals(args[0])) {
            applets.FontTest.main(args);
        }
        if ("starters.Counters".equals(args[0])) {
            starters.Counters.main(args);
        }
        if ("starters.Chart".equals(args[0])) {
            starters.MyChart.main(args);
        }
    }

    /**
     * Creates new form P4Start
     */
    public P4Start() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBox1 = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Locate", "Empire", "Wordgen", "Hexer", "Boxer" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jButton1.setText("...");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addGap(0, 267, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jButton1)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 277, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

  private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
      jButton1.doClick();
  }//GEN-LAST:event_jComboBox1ActionPerformed

  private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
      button1Click();
  }//GEN-LAST:event_jButton1ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    javax.swing.JButton jButton1;
    javax.swing.JComboBox<String> jComboBox1;
    // End of variables declaration//GEN-END:variables

    /**
     *
     */
    public void button1Click() {
        String sel = jComboBox1.getSelectedItem().toString();
        switch (sel) {
            case "Locate": {
                args[0] = "Traveller 5";
                //new Panel4T5Locator();
                Panel4T5Locator.main(args);
                break;
            }
            case "Empire": {
                args[0] = "State of Empire";
                Empire.main(args);
                break;
            }
            case "Boxer": {
                args[0] = "Boxer";
                Boxer.main(args);
                break;
            }
            case "Wordgen": {
                args[0] = sel;
//                Panel4WordGen panel4WordGen = new Panel4WordGen();
                Panel4WordGen.main(new String[]{"Vargr"});
//                panel4WordGen.setSize(600, 600);
//                panel4WordGen.setVisible(true);
                break;
            }
            case "Hexer": {
                args[0] = "Hexer";
                //new Panel4T5Locator();
                dbviewer.Hexer.main(args);
                break;
            }
            default: {
                break;
            }
        }
    }

}
/*
Empire
Boxer
Wordgen
Locate
 */
