/*

 Copyright (C) 2014 Mark Ferguson



 This program is free software: you can redistribute it and/or modify

 it under the terms of the GNU General Public License as published by

 the Free Software Foundation, either version 3 of the License, or

 (at your option) any later version.



 This program is distributed in the hope that it will be useful,

 but WITHOUT ANY WARRANTY; without even the implied warranty of

 MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the

 GNU General Public License for more details.



 You should have received a copy of the GNU General Public License

 along with this program.  If not, see <http://www.gnu.org/licenses/>.

 */
package panels;

import java.awt.BorderLayout;
import javax.swing.JFrame;
import javax.swing.JPanel;

/**
 <p>
 @author maggot
 */
public class Panel4ComboSpinner extends Panel4 {

  Panel4ComboLabel[] p4cl = null;

  /**
   <p>
   @param args strings to start
   */
  public static void main(String[] args) {
    JPanel jp = new Panel4ComboSpinner();
    JFrame jf = new Frame4(jp);
  }

  /**
   Creates new form Panel4ComboSpinner
   */
  public Panel4ComboSpinner() {
    initComponents();
    jSpinner1.setValue(new Integer(1));
  }

  /**
   <p>
   @return name of class
   */
  @Override
  public String toString() {
    String ret = getClass().getName();
    ret = jComboBox1.getSelectedItem().toString() + " x " + jSpinner1.getValue();
    return "" + ret;
  }

  /**
   This method is called from within the constructor to initialize the form.
   WARNING: Do NOT modify this code. The content of this method is always
   regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    jComboBox1 = new javax.swing.JComboBox();
    jSpinner1 = new javax.swing.JSpinner();

    jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Men", "Vehicle", " ", "StarShip", "SpaceCraft", "Vehicle", "World", " ", "Navy", "Marine", "Army", "Scout", "Other", "Merchant", " ", " " }));

    jSpinner1.setModel(new javax.swing.SpinnerNumberModel(0, 0, 20, 1));
    jSpinner1.addChangeListener(new javax.swing.event.ChangeListener() {
      public void stateChanged(javax.swing.event.ChangeEvent evt) {
        jSpinner1StateChanged(evt);
      }
    });

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
    this.setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(jSpinner1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addComponent(jSpinner1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
    );
  }// </editor-fold>//GEN-END:initComponents

  @SuppressWarnings("unchecked")
  private void jSpinner1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSpinner1StateChanged
    int num = (int) jSpinner1.getValue();
    p4cl = new Panel4ComboLabel[num];
    for (int i = 0; i < num; i++) {
      p4cl[i] = new Panel4ComboLabel();
      p4cl[i].jComboBox1.addItem("" + i);
      p4cl[i].jLabel1.setText("" + i);
      //this.add(p4cl[i]);
      add(p4cl[i], BorderLayout.WEST);
      //System.out.print("i" + " = " + i);
      this.validate();
//      dbviewer.DBPublic.getFrame4Panel().validate();
    }
    //System.out.print("this" + " = " + this);
    //System.out.print("num" + " = " + num);
  }//GEN-LAST:event_jSpinner1StateChanged
  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JComboBox jComboBox1;
  private javax.swing.JSpinner jSpinner1;
  // End of variables declaration//GEN-END:variables
}
