/*

 Copyright (C) 2014 Mark Ferguson



 This program is free software: you can redistribute it and/or modify

 it under the terms of the GNU General Public License as published by

 the Free Software Foundation, either version 3 of the License, or

 (at your option) any later version.



 This program is distributed in the hope that it will be useful,

 but WITHOUT ANY WARRANTY; without even the implied warranty of

 MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the

 GNU General Public License for more details.



 You should have received a copy of the GNU General Public License

 along with this program.  If not, see <http://www.gnu.org/licenses/>.

 */
package panels;

import javax.swing.JFrame;
import javax.swing.JPanel;

/**
 <p>
 @author maggot.iiss
 */
public class Panel4Routes extends Panel4 {

  /**
   <p>
   @param args strings to start
   */
  public static void main(String[] args) {
    JPanel jp = new Panel4Routes();
    JFrame jf = new Frame4(jp);
  }

  /**
   Creates new form Panel4Worlds
   */
  public Panel4Routes() {
    super();
    initComponents();
  }

  /**
   <p>
   @param title String to set
   */
  public Panel4Routes(String title) {
    this();
    setName(title);
  }

  /**
   <p>
   @return name of class
   */
  @Override
  public String toString() {
    return "" + getClass().getName() + "[]";
  }

  /**
   This method is called from within the constructor to initialize the form.
   WARNING: Do NOT modify this code. The content of this method is always
   regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    jScrollPane1 = new javax.swing.JScrollPane();
    jTable1 = new javax.swing.JTable();

    setPreferredSize(new java.awt.Dimension(300, 300));

    jScrollPane1.setPreferredSize(new java.awt.Dimension(300, 300));

    jTable1.setModel(new javax.swing.table.DefaultTableModel(
      new Object [][] {
        {"HEX", "1910", "2007", "2005", "1904", "1705", "1307", "1106"},
        {"TYPE", "Capital", "Water", "War", "Trade", "Navy", "Tech", "Miners"},
        {"TL mod", "1", "0.5", "1", "1", "1", "1", "1"},
        {"POP mod", "4", "4.5", "4", "2.5", "4.5", "3", "4.5"},
        {"UWTN", "5", "5", "5", "3.5", "5.5", "4", "5.5"},
        {"Port mod", "0", "0", "0", "0.5", "0", "0", "0"},
        {"WTN", "5", "4.5", "5", "4", "5.5", "4", "5.5"},
        {"Trade Class", "Cp Ri", "Hi In Wa", "Ri", "Fl Ni", "Hi In", "Ag Ni", "Cp Hi In"},
        {"Route", "", null, null, null, null, null, null},
        {"PCI", "5.86K5.86k", "1.43k", "5.86k", "5.86k", "5.86k", "3.66k", "5.86k"},
        {"Trade mod", "1.6", "1.4", "1.6", "0.8", "1.4", "1", "1.4"},
        {"Pop mod", "734M", "3.472B", "600M", "630K", "8.37B", "6.531M", "6.3B"},
        {"GWP(KCr)", "6.88T", "6.95T", "562B", "2.953B", "68.6T", "23.9B", "51.68T"},
        {"WTCM", "0", "0", "0", "0.5", "0.5", "0.50", "0"},
        {"Dist", "-1", "-0.5", "-0.5", "-0.5", "-1", "-0.5", "¬"},
        {"BTN", "8.5Minor", "9Feeder", "8.5Minor", "9.5Feeder", "9Feeder", "9.5Feeder", "¬"},
        {"Cr/yr", "500M-1G", "1-5G", "500M-1G", "5-10G", "1-5G", "5-10G", "¬"},
        {"dt/yr", "50K-100K", "100K-500K", "50K-100K", "500K-1M", "100K-500K", "500K-1M", "¬"},
        {"dt/wk", "1K-5K", "5K-10K", "1K-5K", "10K-50K", "5K-10K", "10K-50K", "¬"},
        {"dt/day", "50-100", "100-500", "50-100", "500-1k", "100-500", "500-1k", "¬"},
        {"Pass/yr", "10K-50K", "10K-50K", "5K-10K", "10K-50K", "5K-10K", "50K-100K", "¬"},
        {"Pass/wk", "500-1K", "500-1K", "100-500", "500-1K", "100-500", "1K-5K", "¬"},
        {"Pass/day", "10-50", "10-50", "5-10", "10-50", "5-10", "50-100", "¬"},
        {"Gravity", "1", "0.77", "0.8", "0.69", "1", "0.7", "1.27"},
        {"Battalions", null, "140", null, null, null, null, null},
        {"Star 1", "F7 V", "F9 V", "G4 V", "M7 V", null, null, null},
        {"Star 2", "M8 D", null, "M3 D(far)", null, null, null, null},
        {"Star 3", "M6 V (far)", null, null, null, null, null, null},
        {"Jump free on", "14+", "14+", "12+", "X", "X", "X", "X"},
        {"StarPort", "A", "C", "B", "A", "A", "B", "A"},
        {"Size", "7", "7", "3", "8", "6", "5", "7"},
        {"Atmosphere", "8", "7", "8", "B", "4", "9", "7"},
        {"Hydrosphere", "8", "A", "4", "3", "6", "2", "7"},
        {"Population", "8", "9", "8", "5", "9", "6", "9"},
        {"Government", "9", "A", "7", "3", "3", "5", "9"},
        {"Law Level", "9", "9", "9", "1", "0", "5", "9"},
        {"TTL", "C", "7", "B", "D", "D", "A", "C"},
        {"GTL", "10", "7", "9+", "10+", "10+", "0", "10"},
        {"Bases", "A", "S", "S", "S", "A", "S", "A"},
        {"Remarks", "Ri Cp", "Hi In Wa", "Ri", "Ni Fl", "Hi In", "Ag Ni", "Hi In Cp"},
        {"Zone", "", "A", "A", null, null, null, null},
        {"Pop mult", "7", "3", "6", "6", "4", "6", "6"},
        {"Belts", "0", "2", "2", "0", "1", "2", "2"},
        {"GGs", "3", "3", "0", "1", "0", "3", "3"},
        {"Alleg", "Im", "Im", "Im", "Im", "Im", "Im", "Im/Zh"},
        {"JUMP", "3", "2", "2", "2", "4", "2", "¬"},
        {"CR", "5", "5", "2", "1", "4", "2", "5"},
        {"Refuel", "", "", "", "", "", "", null},
        {"Traffic", "3d", "2d-2", "3d-4", "3d", "4d", "3d", null},
        {"Area Knowledge", null, null, null, null, null, null, null}
      },
      new String [] {
        "INFO", "Regina", "ROUP*", "Feri*", "Boughene", "EFATE", "Lysen", "Jewel"
      }
    ));
    jScrollPane1.setViewportView(jTable1);

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
    this.setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGap(0, 300, Short.MAX_VALUE)
      .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGap(0, 300, Short.MAX_VALUE)
      .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
          .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 289, Short.MAX_VALUE)
          .addContainerGap()))
    );
  }// </editor-fold>//GEN-END:initComponents
  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JScrollPane jScrollPane1;
  private javax.swing.JTable jTable1;
  // End of variables declaration//GEN-END:variables
}
