/*

 Copyright (C) 2014 Mark Ferguson



 This program is free software: you can redistribute it and/or modify

 it under the terms of the GNU General Public License as published by

 the Free Software Foundation, either version 3 of the License, or

 (at your option) any later version.



 This program is distributed in the hope that it will be useful,

 but WITHOUT ANY WARRANTY; without even the implied warranty of

 MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the

 GNU General Public License for more details.



 You should have received a copy of the GNU General Public License

 along with this program.  If not, see <http://www.gnu.org/licenses/>.

 */
package panels;

import javax.swing.JComboBox;
import javax.swing.JFrame;
import javax.swing.JPanel;

/**
 <p>
 @author Your Name Mark Ferguson maggot.iiss@sky.com
 */
public class Panel4MassCombat extends Panel4 {

  /**
   <p>
   @return name of group
   */
  public static String getTitle() {
    return jTextField1.getText();
  }

  /**
   <p>
   @param args strings to start
   */
  public static void main(String[] args) {
    JPanel jp = new Panel4MassCombat();
    JFrame jf = new Frame4(jp);
  }

  /**
   <p>
   @return group details
   */
  public static String getText() {
    return jTextArea1.getText();
  }
  private String CRLF = "\n";
  private int TS, TotalFront, TotalSupport, TotalTS, TL, MinTL;
  private JComboBox[] boxes;

  /**
   Creates new form Panel4MassCombat
   */
  public Panel4MassCombat() {
    super();
    initComponents();
    jComboBox1.setSelectedIndex(2);
    jButton1.doClick();
    jTextArea1.setText("");
    jComboBox1.setSelectedIndex(1);
    jButton1.doClick();
    jTextArea1.setText("");

    boxes = new JComboBox[]{
      jComboBox1, jComboBox2, jComboBox3, jComboBox4, jComboBox5, jComboBox6,
      jComboBox7, jComboBox8
    };
    for (int i = 1; i < boxes.length; i++) {
      boxes[i].setVisible(false);
    }
  }

  /**
   <p>
   @param tl TechLevel to set jSpinner2
   */
  public Panel4MassCombat(int tl) {
    this();
    jSpinner2.setValue(tl);
  }

  /**
   This method is called from within the constructor to initialize the form.
   WARNING: Do NOT modify this code. The content of this method is always
   regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    jComboBox1 = new javax.swing.JComboBox();
    jComboBox2 = new javax.swing.JComboBox();
    jComboBox3 = new javax.swing.JComboBox();
    jComboBox4 = new javax.swing.JComboBox();
    jComboBox5 = new javax.swing.JComboBox();
    jComboBox6 = new javax.swing.JComboBox();
    jComboBox7 = new javax.swing.JComboBox();
    jComboBox8 = new javax.swing.JComboBox();
    jSpinner1 = new javax.swing.JSpinner();
    jSpinner2 = new javax.swing.JSpinner();
    jScrollPane2 = new javax.swing.JScrollPane();
    jTextArea1 = new javax.swing.JTextArea();
    jButton1 = new javax.swing.JButton();
    jTextField1 = new javax.swing.JTextField();

    setOpaque(false);

    jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "ELEMENT", "Antitank Gun", "APC", "Armoured Car", "Assault Gun", "ATGM", "Battlesuits", "CEV", "Combat Engineers", "Command Post", "Draft Team", "Heavy AAA", "Heavy Artillery", "Heavy Tank", "Heavy Truck", "HSW", "IFW", "Large APC", "Light AAA", "Light Artillery", "Light Tank", "Light Truck", "MANPAD", "MBT", "Medium Tank", "Mobile SAM", "Mortar Team", "Motor ATGM", "Motor Recon", "Mounted Rifles", "Riflemen", "SP AAA", "SP Artillery", "SP Mortar", "Super Tank", "TAD", "Troop Carrier" }));
    jComboBox1.setToolTipText("ELEMENT");
    jComboBox1.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jComboBox1ActionPerformed(evt);
      }
    });

    jComboBox2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "TS*", "(100)", "100", "40", "100", "(240)", "800", "100", "40", "(50)", "2", "(200)", "(300)", "400", "10", "(50)", "200", "100", "40", "(60)", "40", "10", "(100)", "500", "100", "(800)", "(50)", "160", "10", "200", "40", "200", "(500)", "(200)", "20,000", "(50,000)", "20" }));
    jComboBox2.setToolTipText("TS*");
    jComboBox2.setEnabled(false);
    jComboBox2.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jComboBox2ActionPerformed(evt);
      }
    });

    jComboBox3.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Class", "(Arm)", "Arm,Cv,F,T1", "Arm,Cv,F,Rec", "Arm,Art", "(Arm)", "(Air,Arm),F,Rec", "Arm,Eng", "Eng,F", "C31", "T2", "(Air,Arm),F,Rec", "Art", "Arm,F", "T2", "F", "Arm,Cv,F,T1", "Arm,Cv,F,T2", "(Air),F", "Art", "Arm,Cv,F,Rec", "Cv,T1", "(Air)", "Arm,Cav,F", "Arm,Cav,F", "(Air)", "Art", "(Arm),Cv", "Cv,F,Rec", "Cv,F,Rec", "F,Rec", "(Air),F", "Art", "Art", "Arm,Art,Cv,C31,F", "(Air)", "Cav,F,T1" }));
    jComboBox3.setToolTipText("CLASS");
    jComboBox3.setEnabled(false);
    jComboBox3.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jComboBox3ActionPerformed(evt);
      }
    });

    jComboBox4.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "WT", "2", "4", "4", "4", "1", "1", "4", "1", "1", "2", "4", "4", "8", "4", "0.5", "8", "8", "4", "2", "4", "2", "0.5", "8", "8", "4", "1", "2", "1", "2", "1", "8", "8", "4", "16", "16", "4" }));
    jComboBox4.setToolTipText("WT");
    jComboBox4.setEnabled(false);
    jComboBox4.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jComboBox4ActionPerformed(evt);
      }
    });

    jComboBox5.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Mobility", "0", "Mech", "Motor", "Mech", "Foot", "Foot", "Mech", "Foot", "0", "Mtd", "0", "0", "Mech", "Motor", "Foot", "Mech", "Mech", "Mobility", "0", "Mech", "Mobility", "Foot", "Mech", "Mech", "Mobility", "Foot", "Mobility", "Mobility", "Mtd", "Foot", "Mech", "Mech", "Mech", "Mech", "0", "Mech" }));
    jComboBox5.setToolTipText("MOBILITY");
    jComboBox5.setEnabled(false);
    jComboBox5.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jComboBox5ActionPerformed(evt);
      }
    });

    jComboBox6.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Raise", "75", "200", "120", "300", "45", "200", "150", "60", "100", "10", "200", "300", "1000", "300", "50", "400", "300", "70", "60", "140", "25", "37.5", "750", "300", "1000", "25", "140", "25", "100", "60", "500", "500", "200", "6000", "60000", "80" }));
    jComboBox6.setToolTipText("RAISE");
    jComboBox6.setEnabled(false);
    jComboBox6.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jComboBox6ActionPerformed(evt);
      }
    });

    jComboBox7.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Maintain", "5", "10", "6", "15", "9", "40", "7.5", "12", "20", "1", "10", "15", "40", "1.5", "10", "16", "12", "3.5", "4", "7", "2.5", "7.5", "30", "15", "50", "5", "9", "2.5", "20", "12", "25", "20", "0", "200", "2000", "4" }));
    jComboBox7.setToolTipText("MAINTAIN");
    jComboBox7.setEnabled(false);
    jComboBox7.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jComboBox7ActionPerformed(evt);
      }
    });

    jComboBox8.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "TL", "6", "7", "6", "6", "7", "9", "7", "6", "6", "6", "6", "6", "6", "6", "6", "7", "7", "6", "6", "6", "6", "7", "7", "6", "7", "6", "7", "6", "6", "6", "7", "7", "6", "10", "7", "6" }));
    jComboBox8.setToolTipText("TL");
    jComboBox8.setEnabled(false);
    jComboBox8.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jComboBox8ActionPerformed(evt);
      }
    });

    jSpinner1.setModel(new javax.swing.SpinnerNumberModel(Integer.valueOf(1), Integer.valueOf(0), null, Integer.valueOf(1)));
    jSpinner1.setToolTipText("Number of elements");

    jSpinner2.setModel(new javax.swing.SpinnerNumberModel(10, 0, 20, 1));
    jSpinner2.setToolTipText("Tech Level");

    jTextArea1.setColumns(20);
    jTextArea1.setRows(5);
    jTextArea1.addMouseListener(new java.awt.event.MouseAdapter() {
      public void mouseClicked(java.awt.event.MouseEvent evt) {
        jTextArea1MouseClicked(evt);
      }
    });
    jScrollPane2.setViewportView(jTextArea1);

    jButton1.setText("ADD");
    jButton1.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jButton1ActionPerformed(evt);
      }
    });

    jTextField1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
    jTextField1.setText("Tams Troopers");
    jTextField1.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jTextField1ActionPerformed(evt);
      }
    });

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
    this.setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(layout.createSequentialGroup()
            .addComponent(jSpinner1, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(jSpinner2, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 57, Short.MAX_VALUE))
          .addGroup(layout.createSequentialGroup()
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
              .addComponent(jComboBox2, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
              .addComponent(jComboBox3, 0, 127, Short.MAX_VALUE)
              .addComponent(jComboBox4, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
              .addComponent(jComboBox5, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
              .addComponent(jComboBox6, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
              .addComponent(jComboBox7, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
              .addComponent(jComboBox8, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
              .addComponent(jScrollPane2)
              .addGroup(layout.createSequentialGroup()
                .addComponent(jTextField1)
                .addGap(4, 4, 4)))))
        .addContainerGap())
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(jSpinner1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(jSpinner2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(jButton1)
          .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(layout.createSequentialGroup()
            .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(jComboBox4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(jComboBox5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(jComboBox6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(jComboBox7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(jComboBox8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
          .addComponent(jScrollPane2))
        .addContainerGap())
    );
  }// </editor-fold>//GEN-END:initComponents

  private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
    selected(1);
  }//GEN-LAST:event_jComboBox1ActionPerformed

  private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
//    selected(2);
  }//GEN-LAST:event_jComboBox2ActionPerformed

  private void jComboBox3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox3ActionPerformed
//    selected(3);
  }//GEN-LAST:event_jComboBox3ActionPerformed

  private void jComboBox4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox4ActionPerformed
//    selected(4);
  }//GEN-LAST:event_jComboBox4ActionPerformed

  private void jComboBox5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox5ActionPerformed
//    selected(5);
  }//GEN-LAST:event_jComboBox5ActionPerformed

  private void jComboBox6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox6ActionPerformed
//    selected(6);
  }//GEN-LAST:event_jComboBox6ActionPerformed

  private void jComboBox7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox7ActionPerformed
//    selected(7);
  }//GEN-LAST:event_jComboBox7ActionPerformed

  private void jComboBox8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox8ActionPerformed
//    selected(8);
  }//GEN-LAST:event_jComboBox8ActionPerformed

  private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    String spacer = "";
    for (int i = 0; i < 60; i++) {
      spacer += "=";
    }
    jTextArea1.append(""
      + jSpinner1.getValue().toString() + " x "
      + jComboBox1.getSelectedItem().toString() + "/"
      + jSpinner2.getValue().toString() + CRLF
      + "\t\t" + jComboBox2.getToolTipText() + "\t"
      + jComboBox2.getSelectedItem().toString() + CRLF
      + "\t\t" + jComboBox3.getToolTipText() + "\t"
      + jComboBox3.getSelectedItem().toString() + CRLF
      + "\t\t" + jComboBox4.getToolTipText() + "\t"
      + jComboBox4.getSelectedItem().toString() + CRLF
      + "\t\t" + jComboBox5.getToolTipText() + "\t"
      + jComboBox5.getSelectedItem().toString() + CRLF
      + "\t\t" + jComboBox6.getToolTipText() + "\t"
      + "KCr" + jComboBox6.getSelectedItem().toString() + CRLF
      + "\t\t" + jComboBox7.getToolTipText() + "\t"
      + "KCr" + jComboBox7.getSelectedItem().toString() + CRLF
      + "\t\t" + jComboBox8.getToolTipText() + "\t"
      + jComboBox8.getSelectedItem().toString() + CRLF
      + "\tTS\t\t\t" + getTS() + CRLF
      + spacer + CRLF);
  }//GEN-LAST:event_jButton1ActionPerformed

  private void jTextArea1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextArea1MouseClicked
    if (evt.getClickCount() > 2) {
      jTextArea1.setText("");
    }
  }//GEN-LAST:event_jTextArea1MouseClicked

  private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
    // TODO add your handling code here:
  }//GEN-LAST:event_jTextField1ActionPerformed
  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton jButton1;
  private javax.swing.JComboBox jComboBox1;
  private javax.swing.JComboBox jComboBox2;
  private javax.swing.JComboBox jComboBox3;
  private javax.swing.JComboBox jComboBox4;
  private javax.swing.JComboBox jComboBox5;
  private javax.swing.JComboBox jComboBox6;
  private javax.swing.JComboBox jComboBox7;
  private javax.swing.JComboBox jComboBox8;
  private javax.swing.JScrollPane jScrollPane2;
  private javax.swing.JSpinner jSpinner1;
  private javax.swing.JSpinner jSpinner2;
  private static javax.swing.JTextArea jTextArea1;
  private static javax.swing.JTextField jTextField1;
  // End of variables declaration//GEN-END:variables

  private void selected(int par) {
    boxes = new JComboBox[]{
      jComboBox1, jComboBox2, jComboBox3, jComboBox4, jComboBox5, jComboBox6,
      jComboBox7, jComboBox8
    };
    int num = boxes[par - 1].getSelectedIndex();
    for (int i = 0; i < boxes.length; i++) {
      boxes[i].setSelectedIndex(num);
    }
  }

  private String getTS() {
    //int num = 0;
    try {
      TS = Integer.parseInt(jComboBox2.getSelectedItem().toString())
        * (int) jSpinner1.getValue();
      TL = (int) jSpinner2.getValue();
      MinTL = Integer.parseInt(jComboBox8.getSelectedItem().toString());
      //<editor-fold defaultstate="collapsed" desc="DEBUG">
      boolean DEBUG = false;
      if (DEBUG) { // true or false
        //System.out.print("---------------------------");
        //System.out.print("\t" + Thread.currentThread().getStackTrace()[1].getMethodName());
        //System.out.print("" + " = " + TS);
        //System.out.print("" + " = " + TL);
        //System.out.print("" + " = " + MinTL);
        //System.out.print("---------------------------");
      }
//</editor-fold>
      return "" + TechMod(TS, TL, MinTL);
    } catch (NumberFormatException nfe) {
      TS = Integer.parseInt(jComboBox2.getSelectedItem().toString().substring(1,
        jComboBox2.getSelectedItem().toString().length() - 1))
        * (int) jSpinner1.getValue();
      return "(" + TechMod(TS, TL, MinTL) + ")";
    } catch (java.lang.ClassCastException cce) {
      return "(" + TechMod(TS, TL, MinTL) + ")";
    }
  }

  private String TechMod(int ts, int tl, int mintl) {
    int diff = tl - mintl;
    if (diff > 0) {
      for (int i = 0; i < diff; i++) {
        ts *= 2;
        //System.out.print("TS" + " = " + ts);
      }
    }
    return "" + ts;
  }
}
