/*

 Copyright (C) 2014 Mark Ferguson



 This program is free software: you can redistribute it and/or modify

 it under the terms of the GNU General Public License as published by

 the Free Software Foundation, either version 3 of the License, or

 (at your option) any later version.



 This program is distributed in the hope that it will be useful,

 but WITHOUT ANY WARRANTY; without even the implied warranty of

 MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the

 GNU General Public License for more details.



 You should have received a copy of the GNU General Public License

 along with this program.  If not, see <http://www.gnu.org/licenses/>.

 */
package panels;

import javax.swing.JFrame;

/**
 <p>
 @author Your Name Mark Ferguson maggot.iiss@sky.com
 */
public class Panel4Fleets extends Panel4 {

  private static Panel4 jp;
  private static Frame4 jf;
  private int tabs;
  private static Panel4Fleet[] tab;

  /**
   <p>
   @param args strings to start
   */
  public static void main(String[] args) {
    jp = new Panel4Fleets();
    jf = new Frame4(jp, "Fleets");
    jf.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
  }

  /**
   Creates new form Panel4Admiral
   */
  public Panel4Fleets() {
    initComponents();
    System.out.println("after initComponents()");
    tabs = (int) jSpinner1.getValue();
    tab = new Panel4Fleet[tabs];
    for (int i = 0; i < tabs; i++) {
      tab[i] = new Panel4Fleet();
      jtp.addTab("Fleet " + (i + 1), tab[i]);
    }
  }

  /**
   This method is called from within the constructor to initialize the form.
   WARNING: Do NOT modify this code. The content of this method is always
   regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    jSpinner1 = new javax.swing.JSpinner();
    jtp = new javax.swing.JTabbedPane();

    setBackground(new java.awt.Color(0, 0, 0));
    setForeground(java.awt.Color.lightGray);
    setOpaque(true);

    jSpinner1.setModel(new javax.swing.SpinnerNumberModel(Integer.valueOf(2), Integer.valueOf(0), null, Integer.valueOf(1)));
    jSpinner1.addChangeListener(new javax.swing.event.ChangeListener() {
      public void stateChanged(javax.swing.event.ChangeEvent evt) {
        jSpinner1StateChanged(evt);
      }
    });

    jtp.setBackground(new java.awt.Color(0, 0, 0));
    jtp.setForeground(java.awt.Color.lightGray);
    jtp.setOpaque(true);

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
    this.setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addComponent(jSpinner1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addGap(0, 356, Short.MAX_VALUE))
      .addComponent(jtp)
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addComponent(jSpinner1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addGap(0, 0, 0)
        .addComponent(jtp, javax.swing.GroupLayout.DEFAULT_SIZE, 282, Short.MAX_VALUE))
    );
  }// </editor-fold>//GEN-END:initComponents

  private void jSpinner1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSpinner1StateChanged
    int num = (int) jSpinner1.getValue();
    jtp.removeAll();
    tab = new Panel4Fleet[num];
    for (int i = 0; i < num; i++) {
      tab[i] = new Panel4Fleet();
      jtp.addTab("Fleet " + (i + 1), tab[i]);
    }
    jSpinner1.setValue(num);
  }//GEN-LAST:event_jSpinner1StateChanged
  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JSpinner jSpinner1;
  private javax.swing.JTabbedPane jtp;
  // End of variables declaration//GEN-END:variables
}
