/*

 Copyright (C) 2014 Mark Ferguson



 This program is free software: you can redistribute it and/or modify

 it under the terms of the GNU General Public License as published by

 the Free Software Foundation, either version 3 of the License, or

 (at your option) any later version.



 This program is distributed in the hope that it will be useful,

 but WITHOUT ANY WARRANTY; without even the implied warranty of

 MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the

 GNU General Public License for more details.



 You should have received a copy of the GNU General Public License

 along with this program.  If not, see <http://www.gnu.org/licenses/>.

 */
package panels;

import dbviewer.globals.GlobalVariables;
import javax.swing.JFrame;
import javax.swing.JPanel;

/**
 <p>
 @author maggot
 */
public class Panel4Catalogue extends Panel4 {

  /**
   <p>
   @param args strings to start
   */
  public static void main(String[] args) {
    JPanel p4c = new Panel4Catalogue();
    JFrame f4c = new Frame4(p4c);
  }

  /**
   Creates new form Panel4Catalogue
   */
  public Panel4Catalogue() {
    initComponents();
  }

  /**
   This method is called from within the constructor to initialize the form.
   WARNING: Do NOT modify this code. The content of this method is always
   regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    jComboBox1 = new javax.swing.JComboBox();
    jSplitPane1 = new javax.swing.JSplitPane();
    jPanel1 = new javax.swing.JPanel();
    jCheckBox1 = new javax.swing.JCheckBox();
    jCheckBox2 = new javax.swing.JCheckBox();
    jCheckBox3 = new javax.swing.JCheckBox();
    jButton1 = new javax.swing.JButton();
    jTextField1 = new javax.swing.JTextField();
    jPanel2 = new javax.swing.JPanel();
    jScrollPane1 = new javax.swing.JScrollPane();
    jTextArea1 = new javax.swing.JTextArea();

    setLayout(new java.awt.BorderLayout());

    jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Anywhere", "Sector", "SubSector", "SubSectorName", "Hex", "System", "StarPort", "Size", "Atmosphere", "Hydrographics", "Population", "Government", "Law Level", "Tech Level", "Bases", "Remarks", "Zone", "GGs", "Cargo", "Trade", "Star1", "Star2", "Star3", "HW", "AL", "PAG", "Zoned for", "Detail", "Hard1", "Hard2", "Hard3", "Hard4" }));
    add(jComboBox1, java.awt.BorderLayout.PAGE_START);

    jSplitPane1.setDividerLocation(60);
    jSplitPane1.setOpaque(false);

    jCheckBox1.setText("Less");
    jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jCheckBox1ActionPerformed(evt);
      }
    });

    jCheckBox2.setSelected(true);
    jCheckBox2.setText("Equal");
    jCheckBox2.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jCheckBox2ActionPerformed(evt);
      }
    });

    jCheckBox3.setText("More");

    jButton1.setText("GO");
    jButton1.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jButton1ActionPerformed(evt);
      }
    });

    jTextField1.setText("regina");

    javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
    jPanel1.setLayout(jPanel1Layout);
    jPanel1Layout.setHorizontalGroup(
      jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanel1Layout.createSequentialGroup()
        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(jCheckBox1)
          .addComponent(jCheckBox2)
          .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
            .addComponent(jTextField1, javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jCheckBox3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
          .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addGap(0, 0, 0))
    );
    jPanel1Layout.setVerticalGroup(
      jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanel1Layout.createSequentialGroup()
        .addComponent(jCheckBox1)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(jCheckBox2)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(jCheckBox3)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addGap(0, 158, Short.MAX_VALUE))
    );

    jSplitPane1.setLeftComponent(jPanel1);

    jTextArea1.setColumns(20);
    jTextArea1.setRows(5);
    jScrollPane1.setViewportView(jTextArea1);

    javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
    jPanel2.setLayout(jPanel2Layout);
    jPanel2Layout.setHorizontalGroup(
      jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 159, Short.MAX_VALUE)
    );
    jPanel2Layout.setVerticalGroup(
      jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 276, Short.MAX_VALUE)
    );

    jSplitPane1.setRightComponent(jPanel2);

    add(jSplitPane1, java.awt.BorderLayout.CENTER);
  }// </editor-fold>//GEN-END:initComponents

  private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1ActionPerformed
    // TODO add your handling code here:
  }//GEN-LAST:event_jCheckBox1ActionPerformed

  private void jCheckBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox2ActionPerformed
    // TODO add your handling code here:
  }//GEN-LAST:event_jCheckBox2ActionPerformed

  private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    switch (jComboBox1.getSelectedItem().toString()) {
      case "Anywhere": {
        break;
      }
      case "Sector": {
        break;
      }
      case "SubSector": {
        break;
      }
      case "SubSectorName": {
        break;
      }
      case "System": {
        break;
      }
      case "Hex": {
        break;
      }
      case "StarPort": {
        break;
      }
      case "Size": {
        break;
      }
      case "Atmosphere": {
        break;
      }
      case "Hydrographics": {
        break;
      }
      case "Population": {
        break;
      }
      case "Government": {
        break;
      }
      case "": {
        break;
      }
      case "Law Level": {
        break;
      }
      case "Tech Level": {
        break;
      }
      case "Bases": {
        break;
      }
      case "Remarks": {
        break;
      }
      case "Zone": {
        break;
      }
      case "GGs": {
        break;
      }
      case "Cargo": {
        break;
      }
      case "Trade": {
        break;
      }
      case "Star1": {
        break;
      }
      case "Star2": {
        break;
      }
      case "Star3": {
        break;
      }
      case "HW": {
        break;
      }
      case "AL": {
        break;
      }
      case "PAG": {
        break;
      }
      case "Zoned for": {
        break;
      }
      case "Detail": {
        break;
      }
      case "Hard1": {
        break;
      }
      case "Hard2": {
        break;
      }
      case "Hard3": {
        break;
      }
      case "Hard4": {
        break;
      }
    }
    jTextArea1.setText("");
    for (int i = 0; i < Panel4SubSector.worlds.length; i++) {
      if (Panel4SubSector.worlds[i].toLowerCase().contains(jTextField1.getText()
        .toLowerCase())) {
        //System.out.print("\t" + " = " + Panel4SubSector.worlds[i]);
        jTextArea1.append(Panel4SubSector.worlds[i] + GlobalVariables.CRLF);
      }
    }
  }//GEN-LAST:event_jButton1ActionPerformed
  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton jButton1;
  private javax.swing.JCheckBox jCheckBox1;
  private javax.swing.JCheckBox jCheckBox2;
  private javax.swing.JCheckBox jCheckBox3;
  private javax.swing.JComboBox jComboBox1;
  private javax.swing.JPanel jPanel1;
  private javax.swing.JPanel jPanel2;
  private javax.swing.JScrollPane jScrollPane1;
  private javax.swing.JSplitPane jSplitPane1;
  private javax.swing.JTextArea jTextArea1;
  private javax.swing.JTextField jTextField1;
  // End of variables declaration//GEN-END:variables

  private void test() {
    /*
     Anywhere
     Sector
     SubSector
     SubSectorName
     Hex
     System
     StarPort
     Size
     Atmosphere
     Hydrographics
     Population
     Government
     Law Level
     Tech Level
     Bases
     Remarks
     Zone
     GGs
     Cargo
     Trade
     Star1
     Star2
     Star3
     HW
     AL
     PAG
     Zoned for
     Detail
     Hard1
     Hard2
     Hard3
     Hard4
     */
  }
}
