/*

 Copyright (C) 2014 Mark Ferguson



 This program is free software: you can redistribute it and/or modify

 it under the terms of the GNU General Public License as published by

 the Free Software Foundation, either version 3 of the License, or

 (at your option) any later version.



 This program is distributed in the hope that it will be useful,

 but WITHOUT ANY WARRANTY; without even the implied warranty of

 MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the

 GNU General Public License for more details.



 You should have received a copy of the GNU General Public License

 along with this program.  If not, see <http://www.gnu.org/licenses/>.

 */
package panels;

import java.awt.Color;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.geom.AffineTransform;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import static panels.Panel4Piece.im;

/**
 <p>
 @author maggot
 */
public class Panel4PieceInfo extends Panel4 {

  /**
   <p>
   @param args strings to start
   */
  public static void main(String[] args) {
    Panel4Piece.main(args);
    //JPanel jp = new Panel4();
    //JFrame jf = new Frame4(jp);
    //jf.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
  }

  /**
   <p>
   @return jcb
   */
  public static JComboBox getJcb1() {
    return jcb1;
  }

  /**
   <p>
   @param jcb1 JComboBox to set
   */
  public static void setJcb1(JComboBox jcb1) {
    Panel4PieceInfo.jcb1 = jcb1;
  }

  /**
   <p>
   @return jcb2
   */
  public static JComboBox getJcb2() {
    return jcb2;
  }

  /**
   <p>
   @param jcb2 JComboBox to set
   */
  public static void setJcb2(JComboBox jcb2) {
    Panel4PieceInfo.jcb2 = jcb2;
  }

  /**
   <p>
   @return jcb3
   */
  public static JComboBox getJcb3() {
    return jcb3;
  }

  /**
   <p>
   @param jcb3 JComboBox to set
   */
  public static void setJcb3(JComboBox jcb3) {
    Panel4PieceInfo.jcb3 = jcb3;
  }

  /**
   <p>
   @return Label
   */
  public JLabel getLab1() {
    return lab1;
  }

  /**
   <p>
   @param lab1 String to set lab1
   */
  public void setLab1(JLabel lab1) {
    this.lab1 = lab1;
  }

  /**
   <p>
   @return lab2
   */
  public JLabel getLab2() {
    return lab2;
  }

  /**
   <p>
   @param lab2 String to set lab2
   */
  public void setLab2(JLabel lab2) {
    this.lab2 = lab2;
  }

  /**
   <p>
   @return lab3
   */
  public JLabel getLab3() {
    return lab3;
  }

  /**
   <p>
   @param lab3 String to set lab3
   */
  public void setLab3(JLabel lab3) {
    this.lab3 = lab3;
  }

  /**
   Creates new form Panel4PieceInfo
   */
  public Panel4PieceInfo() {
    initComponents();
    //update();
    jcb1.addActionListener(new ActionListener() {
      @Override
      public void actionPerformed(ActionEvent e) {
        //update();
      }
    });
    jcb2.addActionListener(new ActionListener() {
      @Override
      public void actionPerformed(ActionEvent e) {
        //update();
      }
    });
    jcb3.addActionListener(new ActionListener() {
      @Override
      public void actionPerformed(ActionEvent e) {
        //update();
      }
    });

    jcb1.setSelectedIndex(0);
    jcb2.setSelectedIndex(0);
    jcb3.setSelectedIndex(0);
  }

  /**
   <p>
   @return name of class
   */
  @Override
  public String toString() {
    return "" + getClass().getName() + "[]";
  }

  /**
   This method is called from within the constructor to initialize the form.
   WARNING: Do NOT modify this code. The content of this method is always
   regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    jcb1 = new javax.swing.JComboBox();
    lab1 = new javax.swing.JLabel();
    jcb2 = new javax.swing.JComboBox();
    lab2 = new javax.swing.JLabel();
    jcb3 = new javax.swing.JComboBox();
    lab3 = new javax.swing.JLabel();
    jButton1 = new javax.swing.JButton();
    jButton2 = new javax.swing.JButton();
    jButton3 = new javax.swing.JButton();

    jcb1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Foot", "Wheeled", "Tracked", "Water", "Hover", "Grav", "Flying", "Space", " ", "Clear", "Prairie", "Rough", "Mountain", "Marsh", "Swamp", "Forest", "Jungle", "Desert", "Broken" }));
    jcb1.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jcb1ActionPerformed(evt);
      }
    });

    lab1.setText("Traction");

    jcb2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Standard", "Tainted", "Vacuum" }));
    jcb2.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jcb2ActionPerformed(evt);
      }
    });

    lab2.setText("Atmos");

    jcb3.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Single", "Wpn", "Team", "Vehicle" }));
    jcb3.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jcb3ActionPerformed(evt);
      }
    });

    lab3.setText("Unit");

    jButton1.setText("R");
    jButton1.setToolTipText("Rotate");
    jButton1.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jButton1ActionPerformed(evt);
      }
    });

    jButton2.setText("F");
    jButton2.setToolTipText("Flip");
    jButton2.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jButton2ActionPerformed(evt);
      }
    });

    jButton3.setText("M");
    jButton3.setToolTipText("Mirror");
    jButton3.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jButton3ActionPerformed(evt);
      }
    });

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
    this.setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(jcb3, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(jcb2, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(jcb1, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(lab1)
          .addComponent(lab2, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(lab3, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addGap(18, 18, 18)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(jButton1)
          .addComponent(jButton2)
          .addComponent(jButton3)))
    );

    layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jButton1, jButton2, jButton3});

    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
          .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
            .addComponent(lab1, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(jcb1, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
          .addGroup(layout.createSequentialGroup()
            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(3, 3, 3)))
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(jcb2, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(lab2, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(jcb3, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
            .addComponent(lab3, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))))
    );
  }// </editor-fold>//GEN-END:initComponents

  private void jcb1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcb1ActionPerformed
    update();
  }//GEN-LAST:event_jcb1ActionPerformed

  private void jcb2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcb2ActionPerformed
    update();
  }//GEN-LAST:event_jcb2ActionPerformed

  private void jcb3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcb3ActionPerformed
    update();
  }//GEN-LAST:event_jcb3ActionPerformed

  private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    if (Panel4Piece.im[0] != null) {
      Graphics g = im[0].getGraphics();
      Graphics2D g2d = (Graphics2D) im[0].getGraphics(); // Create a Java2D version of g.
      AffineTransform start = g2d.getTransform();
      start.setToQuadrantRotation(1);
      g2d.drawImage(Panel4Piece.im[0], start, null);
      //im[0].getGraphics().drawImage(im[0], F.getX(), F.getY(), jsp);
    }
  }//GEN-LAST:event_jButton1ActionPerformed

  private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
    // TODO add your handling code here:
  }//GEN-LAST:event_jButton2ActionPerformed

  private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
    // TODO add your handling code here:
  }//GEN-LAST:event_jButton3ActionPerformed
  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton jButton1;
  private javax.swing.JButton jButton2;
  private javax.swing.JButton jButton3;
  public static javax.swing.JComboBox jcb1;
  public static javax.swing.JComboBox jcb2;
  public static javax.swing.JComboBox jcb3;
  private javax.swing.JLabel lab1;
  private javax.swing.JLabel lab2;
  private javax.swing.JLabel lab3;
  // End of variables declaration//GEN-END:variables

  /**
   update
   */
  public static void update() {
    String s = jcb1.getSelectedItem().toString();
    Color col = null;
//    //System.out.print("" + " = " + s);
//Foot
    if ("Foot".equals(s)) {
      col = Color.GREEN;
    }
//Wheeled
    if ("Wheeled".equals(s)) {
      col = Color.GRAY;
    }
//Water
    if ("Water".equals(s)) {
      col = Color.BLUE;
    }
//Tracked
    if ("Tracked".equals(s)) {
      col = Color.LIGHT_GRAY;
    }
//Hover
    if ("Hover".equals(s)) {
      col = Color.LIGHT_GRAY;
    }
//Grav
    if ("Grav".equals(s)) {
      col = Color.CYAN;
    }
//Flying
    if ("Flying".equals(s)) {
      col = Color.WHITE;
    }
//Space
    if ("Space".equals(s)) {
      col = Color.BLACK;
    }

    if ("Clear".equals(s)) {
      col = Color.WHITE;
    }
    if ("Prairie".equals(s)) {
      col = Color.GREEN;
    }
    if ("Rough".equals(s)) {
      col = Color.LIGHT_GRAY;
    }
    if ("Mountain".equals(s)) {
      col = Color.GRAY;
    }
    if ("Marsh".equals(s)) {
      col = Color.CYAN;
    }
    if ("Swamp".equals(s)) {
      col = Color.BLUE;
    }
    if ("Forest".equals(s)) {
      col = Color.MAGENTA;
    }
    if ("Jungle".equals(s)) {
      col = Color.LIGHT_GRAY;
    }
    if ("Desert".equals(s)) {
      col = Color.ORANGE;
    }
    if ("Broken".equals(s)) {
      col = Color.BLACK;
    }
    Panel4Piece.FG.setBackground(col);
    Panel4Piece.BG.setBackground(col);
    Panel4Piece.FG.setBackground(col);
    //Panel4Piece.BG.setForeground(col);
    s = jcb2.getSelectedItem().toString();
    //col = null;
    if ("Standard".equals(s)) {
      col = Color.CYAN;
    }
    if ("Tainted".equals(s)) {
      col = Color.LIGHT_GRAY;
    }
    if ("Vacuum".equals(s)) {
      col = Color.WHITE;
    }
    Panel4Piece.p4p.setBackground(col);
    Panel4Piece.F.setBackground(col);
    //Panel4Piece.F.setForeground(col);
    Panel4Piece.B.setBackground(col);
    //Panel4Piece.B.setForeground(col);
    Panel4Piece.U.setText("");
//    Panel4Piece.p4p.setBackground(col);
  }
}
