/*

 Copyright (C) 2014 Mark Ferguson



 This program is free software: you can redistribute it and/or modify

 it under the terms of the GNU General Public License as published by

 the Free Software Foundation, either version 3 of the License, or

 (at your option) any later version.



 This program is distributed in the hope that it will be useful,

 but WITHOUT ANY WARRANTY; without even the implied warranty of

 MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the

 GNU General Public License for more details.



 You should have received a copy of the GNU General Public License

 along with this program.  If not, see <http://www.gnu.org/licenses/>.

 */
package panels;

import javax.swing.JFrame;
import javax.swing.JPanel;

/**
 <p>
 @author maggot
 */
public class Panel4PC extends Panel4 {

  /**
   <p>
   @param args strings to start
   */
  public static void main(String[] args) {
    JPanel jp = new Panel4PC();
    JFrame jf = new Frame4(jp, "Panel4PC");
  }

  /**
   Creates new form Panel4PC
   */
  public Panel4PC() {
    initComponents();
  }

  /**
   This method is called from within the constructor to initialize the form.
   WARNING: Do NOT modify this code. The content of this method is always
   regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    jPanel1 = new javax.swing.JPanel();
    jLabel1 = new javax.swing.JLabel();
    jLabel2 = new javax.swing.JLabel();
    jLabel3 = new javax.swing.JLabel();
    jLabel4 = new javax.swing.JLabel();
    jLabel5 = new javax.swing.JLabel();
    jLabel6 = new javax.swing.JLabel();
    jLabel7 = new javax.swing.JLabel();
    jPanel2 = new javax.swing.JPanel();
    jLabel8 = new javax.swing.JLabel();
    jLabel9 = new javax.swing.JLabel();
    jLabel10 = new javax.swing.JLabel();
    jLabel11 = new javax.swing.JLabel();
    jLabel12 = new javax.swing.JLabel();
    jLabel13 = new javax.swing.JLabel();
    jLabel14 = new javax.swing.JLabel();
    jPanel3 = new javax.swing.JPanel();
    jLabel15 = new javax.swing.JLabel();
    jLabel16 = new javax.swing.JLabel();
    jLabel17 = new javax.swing.JLabel();
    jLabel18 = new javax.swing.JLabel();
    jLabel19 = new javax.swing.JLabel();

    setOpaque(false);

    jLabel1.setIcon(new javax.swing.ImageIcon("D:\\Cyberboard\\BMP\\Har\\Arm\\REDD.gif")); // NOI18N
    jLabel1.setInheritsPopupMenu(false);

    jLabel2.setIcon(new javax.swing.ImageIcon("D:\\Cyberboard\\BMP\\Har\\Com\\Blank.gif")); // NOI18N
    jLabel2.setInheritsPopupMenu(false);

    jLabel3.setIcon(new javax.swing.ImageIcon("D:\\Cyberboard\\BMP\\Har\\Cra\\CM2=50-Columba-12.gif")); // NOI18N
    jLabel3.setInheritsPopupMenu(false);

    jLabel4.setIcon(new javax.swing.ImageIcon("D:\\Cyberboard\\BMP\\Har\\Shi\\Ship.gif")); // NOI18N
    jLabel4.setInheritsPopupMenu(false);

    jLabel5.setIcon(new javax.swing.ImageIcon("D:\\Cyberboard\\BMP\\Har\\Veh\\015-GramAPC-11.gif")); // NOI18N
    jLabel5.setInheritsPopupMenu(false);

    jLabel6.setIcon(new javax.swing.ImageIcon("D:\\Cyberboard\\BMP\\Har\\Wea\\PIS\\GaussPistol4.gif")); // NOI18N
    jLabel6.setInheritsPopupMenu(false);

    jLabel7.setIcon(new javax.swing.ImageIcon("D:\\Cyberboard\\BMP\\Har\\Shi\\BB-Kokirrak-12.gif")); // NOI18N
    jLabel7.setInheritsPopupMenu(false);

    javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
    jPanel1.setLayout(jPanel1Layout);
    jPanel1Layout.setHorizontalGroup(
      jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(jLabel1)
      .addComponent(jLabel2)
      .addComponent(jLabel3)
      .addComponent(jLabel4)
      .addComponent(jLabel5)
      .addComponent(jLabel6)
      .addComponent(jLabel7)
    );
    jPanel1Layout.setVerticalGroup(
      jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanel1Layout.createSequentialGroup()
        .addComponent(jLabel1)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(jLabel2)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(jLabel3)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(jLabel4)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(jLabel5)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(jLabel6)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(jLabel7))
    );

    add(jPanel1, java.awt.BorderLayout.LINE_END);

    jLabel8.setIcon(new javax.swing.ImageIcon("D:\\Cyberboard\\BMP\\Har\\Arm\\REDD.gif")); // NOI18N
    jLabel8.setInheritsPopupMenu(false);

    jLabel9.setIcon(new javax.swing.ImageIcon("D:\\Cyberboard\\BMP\\Har\\Com\\Blank.gif")); // NOI18N
    jLabel9.setInheritsPopupMenu(false);

    jLabel10.setIcon(new javax.swing.ImageIcon("D:\\Cyberboard\\BMP\\Har\\Cra\\CM2=50-Columba-12.gif")); // NOI18N
    jLabel10.setInheritsPopupMenu(false);

    jLabel11.setIcon(new javax.swing.ImageIcon("D:\\Cyberboard\\BMP\\Har\\Shi\\Ship.gif")); // NOI18N
    jLabel11.setInheritsPopupMenu(false);

    jLabel12.setIcon(new javax.swing.ImageIcon("D:\\Cyberboard\\BMP\\Har\\Veh\\015-GramAPC-11.gif")); // NOI18N
    jLabel12.setInheritsPopupMenu(false);

    jLabel13.setIcon(new javax.swing.ImageIcon("D:\\Cyberboard\\BMP\\Har\\Wea\\PIS\\GaussPistol4.gif")); // NOI18N
    jLabel13.setInheritsPopupMenu(false);

    jLabel14.setIcon(new javax.swing.ImageIcon("D:\\Cyberboard\\BMP\\Har\\Shi\\BB-Kokirrak-12.gif")); // NOI18N
    jLabel14.setInheritsPopupMenu(false);

    javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
    jPanel2.setLayout(jPanel2Layout);
    jPanel2Layout.setHorizontalGroup(
      jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(jLabel8)
      .addComponent(jLabel9)
      .addComponent(jLabel10)
      .addComponent(jLabel11)
      .addComponent(jLabel12)
      .addComponent(jLabel13)
      .addComponent(jLabel14)
    );
    jPanel2Layout.setVerticalGroup(
      jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanel2Layout.createSequentialGroup()
        .addComponent(jLabel8)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(jLabel9)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(jLabel10)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(jLabel11)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(jLabel12)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(jLabel13)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(jLabel14))
    );

    add(jPanel2, java.awt.BorderLayout.LINE_START);

    jPanel3.setMinimumSize(new java.awt.Dimension(100, 55));
    jPanel3.setPreferredSize(new java.awt.Dimension(359, 55));

    jLabel15.setIcon(new javax.swing.ImageIcon("D:\\Cyberboard\\BMP\\Har\\Com\\Blank.gif")); // NOI18N
    jLabel15.setInheritsPopupMenu(false);

    jLabel16.setIcon(new javax.swing.ImageIcon("D:\\Cyberboard\\BMP\\Har\\Com\\Blank.gif")); // NOI18N
    jLabel16.setInheritsPopupMenu(false);

    jLabel17.setIcon(new javax.swing.ImageIcon("D:\\Cyberboard\\BMP\\Har\\Com\\Blank.gif")); // NOI18N
    jLabel17.setInheritsPopupMenu(false);

    jLabel18.setIcon(new javax.swing.ImageIcon("D:\\Cyberboard\\BMP\\Har\\Com\\Blank.gif")); // NOI18N
    jLabel18.setInheritsPopupMenu(false);

    jLabel19.setIcon(new javax.swing.ImageIcon("D:\\Cyberboard\\BMP\\Har\\Com\\Blank.gif")); // NOI18N
    jLabel19.setInheritsPopupMenu(false);

    javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
    jPanel3.setLayout(jPanel3Layout);
    jPanel3Layout.setHorizontalGroup(
      jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanel3Layout.createSequentialGroup()
        .addComponent(jLabel15)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(jLabel16)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(jLabel17)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(jLabel18)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(jLabel19)
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );
    jPanel3Layout.setVerticalGroup(
      jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanel3Layout.createSequentialGroup()
        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(jLabel16)
          .addComponent(jLabel15)
          .addComponent(jLabel17)
          .addComponent(jLabel18)
          .addComponent(jLabel19))
        .addGap(0, 0, Short.MAX_VALUE))
    );

    add(jPanel3, java.awt.BorderLayout.PAGE_START);
  }// </editor-fold>//GEN-END:initComponents
  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JLabel jLabel1;
  private javax.swing.JLabel jLabel10;
  private javax.swing.JLabel jLabel11;
  private javax.swing.JLabel jLabel12;
  private javax.swing.JLabel jLabel13;
  private javax.swing.JLabel jLabel14;
  private javax.swing.JLabel jLabel15;
  private javax.swing.JLabel jLabel16;
  private javax.swing.JLabel jLabel17;
  private javax.swing.JLabel jLabel18;
  private javax.swing.JLabel jLabel19;
  private javax.swing.JLabel jLabel2;
  private javax.swing.JLabel jLabel3;
  private javax.swing.JLabel jLabel4;
  private javax.swing.JLabel jLabel5;
  private javax.swing.JLabel jLabel6;
  private javax.swing.JLabel jLabel7;
  private javax.swing.JLabel jLabel8;
  private javax.swing.JLabel jLabel9;
  private javax.swing.JPanel jPanel1;
  private javax.swing.JPanel jPanel2;
  private javax.swing.JPanel jPanel3;
  // End of variables declaration//GEN-END:variables
}
