/*

 Copyright (C) 2014 Mark Ferguson



 This program is free software: you can redistribute it and/or modify

 it under the terms of the GNU General Public License as published by

 the Free Software Foundation, either version 3 of the License, or

 (at your option) any later version.



 This program is distributed in the hope that it will be useful,

 but WITHOUT ANY WARRANTY; without even the implied warranty of

 MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the

 GNU General Public License for more details.



 You should have received a copy of the GNU General Public License

 along with this program.  If not, see <http://www.gnu.org/licenses/>.

 */
package panels;

import java.awt.Color;
import java.awt.Graphics;
import java.awt.Graphics2D;
import javax.swing.BorderFactory;
import javax.swing.JFrame;
import javax.swing.JPanel;
import javax.swing.border.Border;

/**
 <p>
 @author Your Name Mark Ferguson maggot.iiss@sky.com
 */
public class Panel4Grid extends Panel4 {

  static JFrame jf;
  static JPanel jp;
  JPanel[] jps = new JPanel[9];
  int x;
  int y;
  int wid;
  int hgt;
  Graphics g;
  Graphics2D g2 = (Graphics2D) g;

  /**
   <p>
   @param args strings to start
   */
  public static void main(String[] args) {
    jp = new Panel4Grid();
    jf = new Frame4(jp, "Panel4Grid");
  }

  /**
   Creates new form Panel4Grid
   */
  public Panel4Grid() {
    initComponents();
//    jf.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
    jButton1.doClick();
  }

  /**
   <p>
   @param g Graphics
   */
  @Override
  public void paintComponent(Graphics g) {
////    super.paint(g);
//    super.paintComponent(g);
//    for (int i = 0; i < jps.length; i++) {
//      g = jps[i].getGraphics();
//      g.setColor(Color.LIGHT_GRAY);
//      g.drawString(jps[i].getName(), 10, 60);
//      //g2.setPaint(Color.black);
//      //g2.drawString("4518", 100, 100);
//    }
  }

  /**
   This method is called from within the constructor to initialize the form.
   WARNING: Do NOT modify this code. The content of this method is always
   regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    jsx = new javax.swing.JSpinner();
    jsy = new javax.swing.JSpinner();
    jButton1 = new javax.swing.JButton();
    jsv = new javax.swing.JSpinner();

    jsx.setModel(new javax.swing.SpinnerNumberModel(3, 1, 8, 1));
    jsx.setToolTipText("jsx");
    jsx.setValue(3);
    jsx.addChangeListener(new javax.swing.event.ChangeListener() {
      public void stateChanged(javax.swing.event.ChangeEvent evt) {
        jsxStateChanged(evt);
      }
    });

    jsy.setModel(new javax.swing.SpinnerNumberModel(3, 1, 8, 1));
    jsy.setToolTipText("jsy");
    jsy.addChangeListener(new javax.swing.event.ChangeListener() {
      public void stateChanged(javax.swing.event.ChangeEvent evt) {
        jsyStateChanged(evt);
      }
    });

    jButton1.setText("Go");
    jButton1.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jButton1ActionPerformed(evt);
      }
    });

    jsv.setModel(new javax.swing.SpinnerNumberModel(Integer.valueOf(40), Integer.valueOf(10), null, Integer.valueOf(1)));
    jsv.addChangeListener(new javax.swing.event.ChangeListener() {
      public void stateChanged(javax.swing.event.ChangeEvent evt) {
        jsvStateChanged(evt);
      }
    });

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
    this.setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addComponent(jsx, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(jsy, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(jsv, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addGap(18, 18, 18)
        .addComponent(jButton1)
        .addGap(0, 185, Short.MAX_VALUE))
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(jsx, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(jsy, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(jButton1)
          .addComponent(jsv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addGap(0, 277, Short.MAX_VALUE))
    );
  }// </editor-fold>//GEN-END:initComponents

  private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
//    super.paint(g);
    x = (int) jsx.getValue();
    y = (int) jsy.getValue();
    System.out.println("x" + " = " + x);
    wid = (int) jsv.getValue();
    hgt = (int) jsv.getValue();
    jps = new JPanel[x];
    Border b;
    for (int j = 0; j < y; j++) {
      for (int i = 0; i < x; i++) {
        jps[i] = new JPanel();
        jps[i].setBackground(Color.white);
        jps[i].setOpaque(true);
        jps[i].setName("Panel " + i);
        jps[i].setToolTipText(jps[i].getName());
        b = BorderFactory.createEtchedBorder();
        jps[i].setBorder(b);
//        jp.add(jps[i]);
        jps[i].setBounds(wid * i, 40 + (j * hgt), wid, hgt);
      }
    }
    for (JPanel jp1 : jps) {
      g = jp1.getGraphics();
//      g.setColor(Color.LIGHT_GRAY);
//      g.drawString(jp1.getName(), 10, 60);
//      //g2.setPaint(Color.black);
//      //g2.drawString("4518", 100, 100);
    }
    repaint();
  }//GEN-LAST:event_jButton1ActionPerformed

  private void jsxStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jsxStateChanged
    System.out.println("jsxStateChanged");
    x = (int) jsx.getValue();
    y = (int) jsy.getValue();
    wid = (int) jsv.getValue();
    hgt = (int) jsv.getValue();
    jButton1.doClick();
  }//GEN-LAST:event_jsxStateChanged

  private void jsyStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jsyStateChanged
    System.out.println("jsyStateChanged");
    x = (int) jsx.getValue();
    y = (int) jsy.getValue();
    wid = (int) jsv.getValue();
    hgt = (int) jsv.getValue();
    jButton1.doClick();
  }//GEN-LAST:event_jsyStateChanged

  private void jsvStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jsvStateChanged
    System.out.println("jsvStateChanged");
    x = (int) jsx.getValue();
    y = (int) jsy.getValue();
    wid = (int) jsv.getValue();
    hgt = (int) jsv.getValue();
    jButton1.doClick();
  }//GEN-LAST:event_jsvStateChanged
  // Variables declaration - do not modify//GEN-BEGIN:variables
  private static javax.swing.JButton jButton1;
  private javax.swing.JSpinner jsv;
  private javax.swing.JSpinner jsx;
  private javax.swing.JSpinner jsy;
  // End of variables declaration//GEN-END:variables
}
