/*

 Copyright (C) 2014 Mark Ferguson



 This program is free software: you can redistribute it and/or modify

 it under the terms of the GNU General Public License as published by

 the Free Software Foundation, either version 3 of the License, or

 (at your option) any later version.



 This program is distributed in the hope that it will be useful,

 but WITHOUT ANY WARRANTY; without even the implied warranty of

 MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the

 GNU General Public License for more details.



 You should have received a copy of the GNU General Public License

 along with this program.  If not, see <http://www.gnu.org/licenses/>.

 */
package panels;

import dbviewer.globals.GlobalMethods;
import static dbviewer.globals.GlobalMethods.getRoll;
import static dbviewer.globals.GlobalMethods.toHex;
import java.awt.event.MouseEvent;
import javax.swing.DefaultListModel;
import javax.swing.JFrame;
import javax.swing.JList;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import static panels.Panel4NumTypeGroup.groups;
import static panels.Panel4NumTypeGroup.num;
import static panels.Panel4NumTypeGroup.types;

/**
 <p>
 @author Your Name Mark Ferguson maggot.iiss@sky.com
 */
public class Panel4Admiral extends Panel4 {

  private static String arg = "Vilani";
  private static MouseEvent me;
  private static final JList<String> jl = new JList<>();
  private static JFrame jf;
  private static JPanel jp;
  private static final JFrame jfr = new JFrame();
  private static JScrollPane jsp = new JScrollPane(jl);

  /**
   <p>
   @param args strings to start
   */
  public static void main(String[] args) {
//    if (args.length > 0) {
//      arg = args[0];
//    } else {
//      arg = "Zhodani";
//    }
    jp = new Panel4Admiral();
    //jf.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
    jf = new Frame4(jp);
  }

  /**
   Creates new form Panel4Admiral
   */
  @SuppressWarnings("unchecked")
  public Panel4Admiral() {
    super();
    initComponents();
    jLabel4.setText(arg);
    DefaultListModel dlm = new DefaultListModel();
    String[] races = new String[]{"Vilani", "Zhodani", "Vargr",
      "Aslan", "Droyne", "Other",};
    for (int i = 0; i < races.length; i++) {
      dlm.addElement(races[i]);
    }
    jl.setModel(dlm);
    jl.addListSelectionListener(new ListSelectionListener() {
      @Override
      public void valueChanged(ListSelectionEvent e) {
        arg = jLabel4.getText().toString();
        if (e.getValueIsAdjusting() == false) {
//          jf.setVisible(false);
          jLabel4.setText(jl.getSelectedValue().toString());
          arg = jLabel4.getText().toString();
          jTextField1.setText(GlobalMethods.capWords(Panel4WordGenOld.getWord(me,
            arg, jLabel4.getText())));
          for (int i = 0; i < Panel4WordGenOld.jComboBox1.getModel().getSize(); i++) {
            if (jLabel4.getText().equals(Panel4WordGenOld.jComboBox1.getModel().
              getElementAt(i).toString())) {
              System.out.println("" + " = " + Panel4WordGenOld.jComboBox1.
                getModel().getElementAt(i).toString());
              break;
            }
          }
//          Panel4WordGenOld.main(new String[]{
//            T5 + "/CSV/imp-" + (jLabel4.getText().substring(0, 3).toLowerCase())});
////            Panel4WordGenOld.jf.setVisible(false);
//          Panel4WordGenOld.jComboBox1.setSelectedItem(jLabel4.getText());
        }
        jfr.setVisible(false);
      }
    });
    jComboBox1.setSelectedIndex(0);
    jTextField7MouseClicked(me);
  }

  static void calc() {
    num = Integer.parseInt(Num.getValue().toString());
    types = Integer.parseInt(Types.getValue().toString());
    groups = Integer.parseInt(Groups.getValue().toString());

    if (types > num) {
      types = num;
    }
    if (groups > num) {
      groups = num;
    }

    if (types < 1 & num > 0) {
      types = 1;
      Types.setValue(types);
    }
    if (groups == 0 & num > 0) {
      groups = 1;
      Groups.setValue(groups);
    }

    Num.setValue(num);
    Types.setValue(types);
    Groups.setValue(groups);

  }

  /**
   This method is called from within the constructor to initialize the form.
   WARNING: Do NOT modify this code. The content of this method is always
   regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    jTextField1 = new javax.swing.JTextField();
    jLabel4 = new javax.swing.JLabel();
    jTextField2 = new javax.swing.JTextField();
    jTextField3 = new javax.swing.JTextField();
    jTextField4 = new javax.swing.JTextField();
    jLabel1 = new javax.swing.JLabel();
    jLabel2 = new javax.swing.JLabel();
    jLabel3 = new javax.swing.JLabel();
    panel41 = new panels.Panel4();
    jComboBox1 = new javax.swing.JComboBox();
    jTextField6 = new javax.swing.JTextField();
    jTextField7 = new javax.swing.JTextField();
    jLabel8 = new javax.swing.JLabel();
    panel42 = new panels.Panel4();
    jLabel5 = new javax.swing.JLabel();
    jLabel6 = new javax.swing.JLabel();
    jLabel7 = new javax.swing.JLabel();
    Num = new javax.swing.JSpinner();
    Types = new javax.swing.JSpinner();
    Groups = new javax.swing.JSpinner();

    jTextField1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
    jTextField1.setForeground(new java.awt.Color(255, 0, 0));
    jTextField1.setText("Adama");

    jLabel4.setForeground(new java.awt.Color(255, 0, 0));
    jLabel4.setText("Vilani");
    jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
      public void mouseClicked(java.awt.event.MouseEvent evt) {
        jLabel4MouseClicked(evt);
      }
    });

    setBackground(new java.awt.Color(0, 0, 0));
    setForeground(java.awt.Color.lightGray);
    setOpaque(true);

    jTextField2.setForeground(new java.awt.Color(255, 0, 0));
    jTextField2.setText("0");

    jTextField3.setForeground(new java.awt.Color(255, 0, 0));
    jTextField3.setText("0");

    jTextField4.setForeground(new java.awt.Color(255, 0, 0));
    jTextField4.setText("0");

    jLabel1.setForeground(java.awt.Color.green);
    jLabel1.setText("Precedence");
    jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
      public void mouseClicked(java.awt.event.MouseEvent evt) {
        jLabel1MouseClicked(evt);
      }
    });

    jLabel2.setForeground(java.awt.Color.green);
    jLabel2.setText("Planning");
    jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
      public void mouseClicked(java.awt.event.MouseEvent evt) {
        jLabel2MouseClicked(evt);
      }
    });

    jLabel3.setForeground(java.awt.Color.green);
    jLabel3.setText("Tactical");
    jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
      public void mouseClicked(java.awt.event.MouseEvent evt) {
        jLabel3MouseClicked(evt);
      }
    });

    jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Vilani", "Zhodani", "Vargr", "Aslan", "Droyne", "Other" }));
    jComboBox1.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jComboBox1ActionPerformed(evt);
      }
    });

    jTextField6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
    jTextField6.addMouseListener(new java.awt.event.MouseAdapter() {
      public void mouseClicked(java.awt.event.MouseEvent evt) {
        jTextField6MouseClicked(evt);
      }
    });

    jTextField7.addMouseListener(new java.awt.event.MouseAdapter() {
      public void mouseClicked(java.awt.event.MouseEvent evt) {
        jTextField7MouseClicked(evt);
      }
    });

    javax.swing.GroupLayout panel41Layout = new javax.swing.GroupLayout(panel41);
    panel41.setLayout(panel41Layout);
    panel41Layout.setHorizontalGroup(
      panel41Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(panel41Layout.createSequentialGroup()
        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(jTextField7, javax.swing.GroupLayout.DEFAULT_SIZE, 64, Short.MAX_VALUE))
    );
    panel41Layout.setVerticalGroup(
      panel41Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(panel41Layout.createSequentialGroup()
        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addGap(0, 0, Short.MAX_VALUE))
      .addGroup(panel41Layout.createSequentialGroup()
        .addGroup(panel41Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );

    jLabel8.setForeground(java.awt.Color.lightGray);
    jLabel8.setText("jLabel8");

    jLabel5.setForeground(java.awt.Color.lightGray);
    jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
    jLabel5.setText("SQUADRONS");

    jLabel6.setForeground(java.awt.Color.lightGray);
    jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
    jLabel6.setText("Types");

    jLabel7.setForeground(java.awt.Color.lightGray);
    jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
    jLabel7.setText("Groups");

    Num.setModel(new javax.swing.SpinnerNumberModel(Integer.valueOf(10), Integer.valueOf(0), null, Integer.valueOf(1)));
    Num.addChangeListener(new javax.swing.event.ChangeListener() {
      public void stateChanged(javax.swing.event.ChangeEvent evt) {
        NumStateChanged(evt);
      }
    });

    Types.setModel(new javax.swing.SpinnerNumberModel(Integer.valueOf(1), Integer.valueOf(0), null, Integer.valueOf(1)));
    Types.addChangeListener(new javax.swing.event.ChangeListener() {
      public void stateChanged(javax.swing.event.ChangeEvent evt) {
        TypesStateChanged(evt);
      }
    });

    Groups.setModel(new javax.swing.SpinnerNumberModel(Integer.valueOf(1), Integer.valueOf(0), null, Integer.valueOf(1)));
    Groups.addChangeListener(new javax.swing.event.ChangeListener() {
      public void stateChanged(javax.swing.event.ChangeEvent evt) {
        GroupsStateChanged(evt);
      }
    });

    javax.swing.GroupLayout panel42Layout = new javax.swing.GroupLayout(panel42);
    panel42.setLayout(panel42Layout);
    panel42Layout.setHorizontalGroup(
      panel42Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel42Layout.createSequentialGroup()
        .addGroup(panel42Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(jLabel5)
          .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel42Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
        .addGroup(panel42Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(Types, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(Num, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(Groups, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addGap(24, 24, 24))
    );
    panel42Layout.setVerticalGroup(
      panel42Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(panel42Layout.createSequentialGroup()
        .addGroup(panel42Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(jLabel5)
          .addComponent(Num, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addGap(2, 2, 2)
        .addGroup(panel42Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(jLabel6)
          .addComponent(Types, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addGap(2, 2, 2)
        .addGroup(panel42Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(jLabel7)
          .addComponent(Groups, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addGap(2, 2, 2))
    );

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
    this.setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
              .addComponent(jLabel1)
              .addComponent(jLabel2)
              .addComponent(jLabel3))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
              .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
              .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
              .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(panel42, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
          .addComponent(panel41, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        .addGap(49, 49, 49))
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
          .addComponent(panel41, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(jLabel8))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(panel42, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addGroup(layout.createSequentialGroup()
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
              .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
              .addComponent(jLabel1))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
              .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
              .addComponent(jLabel2))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
              .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
              .addComponent(jLabel3))))
        .addContainerGap(54, Short.MAX_VALUE))
    );
  }// </editor-fold>//GEN-END:initComponents

  private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
    // Change precedence 3d-3
    jTextField2.setText("" + (GlobalMethods.getRoll(3) - 3));
    jLabel2MouseClicked(evt);
  }//GEN-LAST:event_jLabel1MouseClicked

  private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
    // Change planning 2d
    String PF = "5";
    int roll = (GlobalMethods.getRoll(2));
    String result = "";
    jTextField3.setText("" + roll);
    jLabel3MouseClicked(evt);
  }//GEN-LAST:event_jLabel2MouseClicked

  private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
    // Change tactical 1d
    String TF = "-2";
    int roll = (GlobalMethods.getRoll(1));
    String result = "";
    jTextField4.setText("" + roll);
  }//GEN-LAST:event_jLabel3MouseClicked

  private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
    // Change race for random name generation
    me = evt;
    if (evt.getClickCount() > 1) {
      jfr.add(jsp);
      jfr.setBounds(250, 0, 75, 150);
      jfr.setVisible(true);
    } else {
      jTextField1.setText(GlobalMethods.capWords(Panel4WordGenOld.getWord(evt, arg,
        jLabel4.getText())));
      jfr.setVisible(false);
    }
    jLabel1MouseClicked(me);
    jLabel2MouseClicked(me);
    jLabel3MouseClicked(me);
  }//GEN-LAST:event_jLabel4MouseClicked

  private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
    jTextField6MouseClicked(me);
    jLabel8.setText(Panel4Locator.getString());
  }//GEN-LAST:event_jComboBox1ActionPerformed

  private void jTextField6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField6MouseClicked
    String word = Panel4WordGenOld.getWord(me, jComboBox1.getSelectedItem()
      .toString(), null);
    this.jTextField6.setText(word);
    this.jTextField6.setSelectionStart(0);
    this.jTextField6.setSelectionEnd(jTextField1.getText().length());
    jTextField7MouseClicked(evt);
  }//GEN-LAST:event_jTextField6MouseClicked

  private void jTextField7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField7MouseClicked
    String upp = "";
    for (int i = 0; i < 6; i++) {
      int n = getRoll(2);
      upp += toHex(n);
    }
    jTextField7.setText(upp);
    jLabel1MouseClicked(evt);
  }//GEN-LAST:event_jTextField7MouseClicked

  private void NumStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_NumStateChanged
    calc();
  }//GEN-LAST:event_NumStateChanged

  private void TypesStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_TypesStateChanged
    calc();
  }//GEN-LAST:event_TypesStateChanged

  private void GroupsStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_GroupsStateChanged
    calc();
  }//GEN-LAST:event_GroupsStateChanged

  // Variables declaration - do not modify//GEN-BEGIN:variables
  static javax.swing.JSpinner Groups;
  static javax.swing.JSpinner Num;
  static javax.swing.JSpinner Types;
  static javax.swing.JComboBox jComboBox1;
  private javax.swing.JLabel jLabel1;
  private javax.swing.JLabel jLabel2;
  private javax.swing.JLabel jLabel3;
  private javax.swing.JLabel jLabel4;
  private javax.swing.JLabel jLabel5;
  private javax.swing.JLabel jLabel6;
  private javax.swing.JLabel jLabel7;
  private javax.swing.JLabel jLabel8;
  private javax.swing.JTextField jTextField1;
  static javax.swing.JTextField jTextField2;
  static javax.swing.JTextField jTextField3;
  static javax.swing.JTextField jTextField4;
  static javax.swing.JTextField jTextField6;
  private javax.swing.JTextField jTextField7;
  private panels.Panel4 panel41;
  private panels.Panel4 panel42;
  // End of variables declaration//GEN-END:variables
}
