/*

 Copyright (C) 2014 Mark Ferguson



 This program is free software: you can redistribute it and/or modify

 it under the terms of the GNU General Public License as published by

 the Free Software Foundation, either version 3 of the License, or

 (at your option) any later version.



 This program is distributed in the hope that it will be useful,

 but WITHOUT ANY WARRANTY; without even the implied warranty of

 MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the

 GNU General Public License for more details.



 You should have received a copy of the GNU General Public License

 along with this program.  If not, see <http://www.gnu.org/licenses/>.

 */
package dbviewer;

import dbviewer.globals.GlobalVariables;
import java.awt.Color;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.DefaultListModel;
import javax.swing.JFrame;
import javax.swing.JPanel;
import javax.swing.ListModel;
import panels.Frame4;
import panels.Panel4;

/**

 @author Your Name Mark Ferguson maggot.iiss@sky.com
 */
public class BmpCheck extends Panel4 {

  private static String FS = GlobalVariables.FS;

  /**

   @param args strings to start
   */
  @SuppressWarnings("unchecked")
  public static void main(String[] args) {
    JPanel jp = new BmpCheck();
    JFrame jf = new Frame4(jp);
    jf.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
    File file = new File(GlobalVariables.BMP);
    String[] files = file.list();
    DefaultListModel<String> lm = new DefaultListModel<>();
    for (int i = 0; i < files.length; i++) {
      if (files[i].endsWith(".gif")) {
        String path = GlobalVariables.BMP + FS + files[i];
//        System.out.println("" + " = " + path);
        lm.addElement(path);
      }
    }
    jList1.setModel((ListModel<String>) lm);
    jf.setBackground(Color.blue);
    jp.setBackground(Color.blue);
    jLabel1.setBackground(Color.blue);
    jList1.setSelectedIndex(0);
  }

  /**
   Creates new form BmpCheck
   */
  public BmpCheck() {
    initComponents();
  }

  /**
   This method is called from within the constructor to initialize the form.
   WARNING: Do NOT modify this code. The content of this method is always
   regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    jScrollPane1 = new javax.swing.JScrollPane();
    jList1 = new javax.swing.JList();
    jLabel1 = new javax.swing.JLabel();

    jList1.addMouseListener(new java.awt.event.MouseAdapter() {
      public void mouseClicked(java.awt.event.MouseEvent evt) {
        jList1MouseClicked(evt);
      }
    });
    jList1.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
      public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
        jList1ValueChanged(evt);
      }
    });
    jScrollPane1.setViewportView(jList1);

    jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    jLabel1.setOpaque(true);

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
    this.setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 126, Short.MAX_VALUE))
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
      .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
    );
  }// </editor-fold>//GEN-END:initComponents

  private void jList1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jList1MouseClicked
    showPic();
  }//GEN-LAST:event_jList1MouseClicked

  private void jList1ValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_jList1ValueChanged
    showPic();
  }//GEN-LAST:event_jList1ValueChanged
  // Variables declaration - do not modify//GEN-BEGIN:variables
  static javax.swing.JLabel jLabel1;
  static javax.swing.JList jList1;
  private javax.swing.JScrollPane jScrollPane1;
  // End of variables declaration//GEN-END:variables

  private void showPic() {
    super.paintComponent(jLabel1.getGraphics());
    File f = new File(jList1.getSelectedValue().toString());
    try {
      BufferedImage image = ImageIO.read(f);

      jLabel1.getGraphics().drawImage(image, 100, 100, null);
    } catch (IOException ex) {
      Logger.getLogger(BmpCheck.class.getName()).log(Level.SEVERE, null, ex);
    }
  }

}
